<?php

namespace Database\Seeders;

use DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Faker\Factory as Faker;

class KelurahanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $faker = Faker::create('id_ID');

        $data_kelurahan = [
            'Tlogosari',
            'Pedurungan',
            'Bangetayu',
            'Sendangguwo',
            'Genuksari',
            'Kaligawe',
            'Gayamsari',
            'Sambirejo',
            'Karangtempel',
            'Peterongan',
            'Kuningan',
            'Mlatiharjo',
            'Mlatibaru',
            'Lamper Kidul',
            'Lamper Tengah',
            'Lamper Lor',
            'Pleburan',
            'Bulustalan',
            'Randusari',
            'Mugassari',
            'Karangkidul',
            'Jagalan',
            'Rejomulyo',
            'Purwodinatan',
            'Kranggan',
            'Sekayu',
            'Pandansari',
            'Brumbungan',
            'Purwosari',
            'Wonodri',
            'Kedungmundu',
            'Meteseh',
            'Tembalang',
            'Bulusan',
            'Mangunharjo',
            'Mangunsari',
            'Sekaran',
            'Pudakpayung',
            'Kramas',
            'Jatingaleh',
            'Sampangan',
            'Gajahmungkur',
            'Bendan Duwur',
            'Bendan Ngisor',
            'Karangrejo',
            'Srondol Wetan',
            'Srondol Kulon',
            'Pedalangan',
            'Ngesrep',
            'Sumurboto',
            'Ngaliyan',
            'Tambak Aji',
            'Wonosari',
            'Kalipancur',
            'Purwoyoso',
            'Beringin',
            'Mangkang Wetan',
            'Mangkang Kulon',
            'Wadungpandan',
            'Ngadirgo',
            'Plamongan Sari',
            'Rowosari',
            'Sendangmulyo',
            'Tegalsari',
            'Tegowanu',
            'Karanganyar',
            'Karangdoro',
            'Gedawang',
            'Gisikdrono',
            'Ngemplak Simongan',
            'Bojongsalaman',
            'Krobokan',
            'Kembangarum',
            'Salamanmloyo',
            'Kalibanteng Kulon',
            'Kalibanteng Wetan',
            'Tawangsari',
            'Tambakharjo',
            'Tanjungmas',
            'Kuningan Timur',
            'Plombokan',
            'Panggung Kidul',
            'Bulu Lor',
            'Panggung Lor',
            'Dadapsari',
            'Kuningan Barat',
            'Kuningan Utara',
            'Barusari',
            'Karangayu',
            'Tawangmas',
            'Purwoyoso Utara',
            'Wonosari Barat',
            'Tambakaji',
            'Podorejo',
            'Bringin',
            'Ngalian',
            'Kudu',
            'Wates',
            'Tugurejo',
            'Karangmalang',
            'Gondoriyo',
            'Sambiroto',
            'Tinjomoyo',
            'Jomblang',
            'Kandri',
            'Sedayu',
            'Pesantren',
            'Kalisari',
            'Tegalsari Timur',
            'Tegalsari Barat',
            'Pandean',
            'Bugangan',
            'Barusari Selatan',
            'Barusari Tengah',
            'Barusari Utara',
            'Candi',
            'Gisikdrono Timur',
            'Gisikdrono Barat',
            'Kuningan Tengah',
            'Kuningan Timur Laut',
            'Kuningan Selatan',
            'Karangrejo Barat',
            'Karangrejo Timur',
            'Lamper Lor Timur',
            'Lamper Lor Barat',
            'Lamper Tengah Timur',
            'Lamper Tengah Barat',
            'Sambiroto Timur',
            'Sambiroto Barat',
            'Sekaran Barat',
            'Sekaran Timur',
            'Tinjomoyo Atas',
            'Tinjomoyo Bawah',
            'Kudusari',
            'Kaligawe Timur',
            'Kaligawe Barat',
            'Meteseh Barat',
            'Meteseh Timur',
            'Gajahmungkur Utara',
            'Gajahmungkur Selatan',
            'Pleburan Timur',
            'Pleburan Barat',
            'Pudakpayung Timur',
            'Pudakpayung Barat',
            'Tlogosari Wetan',
            'Tlogosari Kulon',
            'Pedurungan Lor',
            'Pedurungan Kidul',
            'Sendangmulyo Barat',
            'Sendangmulyo Timur',
            'Bulusan Atas',
            'Bulusan Bawah',
            'Ngesrep Barat',
            'Ngesrep Timur',
            'Sumurboto Selatan',
            'Sumurboto Utara',
            'Sambirejo Utara',
            'Sambirejo Selatan',
            'Karangtempel Timur',
            'Karangtempel Barat',
            'Gayamsari Utara',
            'Gayamsari Selatan',
            'Mugassari Timur',
            'Mugassari Barat',
            'Karangkidul Timur',
            'Karangkidul Barat',
            'Rejomulyo Timur',
            'Rejomulyo Barat',
            'Genuksari Timur',
            'Genuksari Barat',
            'Tawangsari Timur',
            'Tawangsari Barat',
            'Tambakharjo Timur',
            'Tambakharjo Barat',
            'Ngaliyan Timur',
            'Ngaliyan Barat',
            'Pandean Barat',
            'Pandean Timur',
            'Tanjungmas Timur',
            'Tanjungmas Barat',
            'Bulu Lor Timur',
            'Bulu Lor Barat',
            'Dadapsari Timur',
            'Dadapsari Barat',
            'Plombokan Barat',
            'Plombokan Timur',
            'Panggung Lor Timur',
            'Panggung Lor Barat',
            'Sedayu Timur',
            'Sedayu Barat',
            'Pesantren Timur',
            'Pesantren Barat'
        ];
        // id kecamatan
        $kecamatan_id = DB::table('kecamatan')->pluck('id');

        foreach (range(1, 300) as $i) {
            DB::table('kelurahan')->insert([
                'kecamatan_id' => $faker->randomElement($kecamatan_id),
                'kelurahan_nama' => $faker->randomElement($data_kelurahan),
                'kelurahan_code' => $faker->numberBetween(10, 99),
                'created_at' => now(),
                'updated_at' => now(),
            ]);
        }
    }
}
